// <auto-generated />
namespace TruckEvent.WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fkVendaEEvento4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fkVendaEEvento4));
        
        string IMigrationMetadata.Id
        {
            get { return "201705060204295_fkVendaEEvento4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
